git:
  remote:
    upstream: 'mongodb/docs'
    tools: 'mongodb/docs-tools'
project:
  name: 'primer'
  tag: 'primer'
  url: 'http://docs.mongodb.org/primer'
  title: 'MongoDB Primer'
  branched: false
  editions:
    - name: shell
      branched: false
    - name: python
      branched: false
    - name: node
      branched: false
    - name: cpp
      branched: false
    - name: java
      branched: false
    - name: csharp
      branched: false
version:
  release: '3.0.1'
  branch: '3.0'
system:
  files:
    - 'integration.yaml'
    - 'push.yaml'
    - 'sphinx_local.yaml'
    - intersphinx:
        - 'intersphinx.yaml'
        - 'intersphinx-local.yaml'
    - migrations:
        - 'primer-migrations-complex.yaml'
        - 'primer-migrations-simple.yaml'
        - 'primer-migrations-cpp-examples.yaml'
        - 'primer-migrations-java-examples.yaml'
        - 'primer-migrations-csharp-examples.yaml'
assets:
  - branch: master
    path: build/docs-tools
    repository: https://github.com/mongodb/docs-tools.git
  - branch: primer-dataset
    path: build/dataset
    repository: https://github.com/mongodb/docs-assets.git
  - branch: master
    path: build/cpp-examples
    repository: https://github.com/mongodb/mongo-cxx-driver.git
  - branch: master
    path: build/java-examples
    repository: https://github.com/mongodb/mongo-java-driver.git
  - branch: master
    path: build/csharp-examples
    repository: https://github.com/mongodb/mongo-csharp-driver.git
paths:
  output: 'build'
  source: 'source'
  includes: 'source/includes'
  images: 'source/images'
  tools: 'bin'
  buildsystem: 'build/docs-tools'
  builddata: 'config'
  locale: 'locale'
...
