---
source: build/csharp-examples/src/MongoDB.Driver.Examples/AggregatePrimer.cs
target: includes/example-prereq-csharp-AggregatePrimer.cs
truncate:
   start-after: 14
   end-before: 19
---
source: build/csharp-examples/src/MongoDB.Driver.Examples/AggregatePrimer.cs
target: includes/example-csharp-group-documents-by-a-field-and-calculate-count.cs
transform: 
  regex: "^            "
  replace: ""
truncate:
   start-after: 30
   end-before: 34
---
source: build/csharp-examples/src/MongoDB.Driver.Examples/AggregatePrimer.cs
target: includes/example-csharp-group-documents-by-a-field-and-calculate-count-results.rst
transform: 
  - regex: "^            "
    replace: ""
truncate:
   start-after: 36
   end-before: 47
---
source: build/csharp-examples/src/MongoDB.Driver.Examples/AggregatePrimer.cs
target: includes/example-csharp-filter-and-group-documents.cs
transform: 
  regex: "^            "
  replace: ""
truncate:
   start-after: 56
   end-before: 62
---
source: build/csharp-examples/src/MongoDB.Driver.Examples/AggregatePrimer.cs
target: includes/example-csharp-filter-and-group-documents-results.rst
transform: 
  - regex: "^            "
    replace: ""
truncate:
   start-after: 64
   end-before: 74
---
source: build/csharp-examples/src/MongoDB.Driver.Examples/InsertPrimer.cs
target: includes/example-prereq-csharp-InsertPrimer.cs
truncate:
   start-after: 14
   end-before: 19
---
source: build/csharp-examples/src/MongoDB.Driver.Examples/InsertPrimer.cs
target: includes/example-csharp-insert-a-document.cs
transform: 
  regex: "^            "
  replace: ""
truncate:
   start-after: 31
   end-before: 66
---
source: build/csharp-examples/src/MongoDB.Driver.Examples/InsertPrimer.cs
target: includes/example-csharp-insert-a-document-post.rst
transform: 
  regex: "^            // @post: "
  replace: ""
truncate:
   start-after: 67
   end-before: 69
---
source: build/csharp-examples/src/MongoDB.Driver.Examples/QueryPrimer.cs
target: includes/example-prereq-csharp-QueryPrimer.cs
truncate:
   start-after: 14
   end-before: 22
---
source: build/csharp-examples/src/MongoDB.Driver.Examples/QueryPrimer.cs
target: includes/example-csharp-query-all.cs
transform: 
  regex: "^            "
  replace: ""
truncate:
   start-after: 33
   end-before: 49
---
source: build/csharp-examples/src/MongoDB.Driver.Examples/QueryPrimer.cs
target: includes/example-csharp-query-all-results.rst
transform: 
  - regex: "^            "
    replace: ""
truncate:
   start-after: 51
   end-before: 53
---
source: build/csharp-examples/src/MongoDB.Driver.Examples/QueryPrimer.cs
target: includes/example-csharp-logical-and.cs
transform: 
  regex: "^            "
  replace: ""
truncate:
   start-after: 62
   end-before: 67
---
source: build/csharp-examples/src/MongoDB.Driver.Examples/QueryPrimer.cs
target: includes/example-csharp-logical-and-results.rst
transform: 
  - regex: "^            "
    replace: ""
truncate:
   start-after: 69
   end-before: 71
---
source: build/csharp-examples/src/MongoDB.Driver.Examples/QueryPrimer.cs
target: includes/example-csharp-logical-or.cs
transform: 
  regex: "^            "
  replace: ""
truncate:
   start-after: 80
   end-before: 85
---
source: build/csharp-examples/src/MongoDB.Driver.Examples/QueryPrimer.cs
target: includes/example-csharp-logical-or-results.rst
transform: 
  - regex: "^            "
    replace: ""
truncate:
   start-after: 87
   end-before: 89
---
source: build/csharp-examples/src/MongoDB.Driver.Examples/QueryPrimer.cs
target: includes/example-csharp-query-top-level-field.cs
transform: 
  regex: "^            "
  replace: ""
truncate:
   start-after: 98
   end-before: 102
---
source: build/csharp-examples/src/MongoDB.Driver.Examples/QueryPrimer.cs
target: includes/example-csharp-query-top-level-field-results.rst
transform: 
  - regex: "^            "
    replace: ""
truncate:
   start-after: 104
   end-before: 106
---
source: build/csharp-examples/src/MongoDB.Driver.Examples/QueryPrimer.cs
target: includes/example-csharp-query-embedded-document.cs
transform: 
  regex: "^            "
  replace: ""
truncate:
   start-after: 115
   end-before: 119
---
source: build/csharp-examples/src/MongoDB.Driver.Examples/QueryPrimer.cs
target: includes/example-csharp-query-embedded-document-results.rst
transform: 
  - regex: "^            "
    replace: ""
truncate:
   start-after: 121
   end-before: 123
---
source: build/csharp-examples/src/MongoDB.Driver.Examples/QueryPrimer.cs
target: includes/example-csharp-query-field-in-array.cs
transform: 
  regex: "^            "
  replace: ""
truncate:
   start-after: 132
   end-before: 136
---
source: build/csharp-examples/src/MongoDB.Driver.Examples/QueryPrimer.cs
target: includes/example-csharp-query-field-in-array-results.rst
transform: 
  - regex: "^            "
    replace: ""
truncate:
   start-after: 138
   end-before: 140
---
source: build/csharp-examples/src/MongoDB.Driver.Examples/QueryPrimer.cs
target: includes/example-csharp-greater-than.cs
transform: 
  regex: "^            "
  replace: ""
truncate:
   start-after: 149
   end-before: 153
---
source: build/csharp-examples/src/MongoDB.Driver.Examples/QueryPrimer.cs
target: includes/example-csharp-greater-than-results.rst
transform: 
  - regex: "^            "
    replace: ""
truncate:
   start-after: 155
   end-before: 157
---
source: build/csharp-examples/src/MongoDB.Driver.Examples/QueryPrimer.cs
target: includes/example-csharp-less-than.cs
transform: 
  regex: "^            "
  replace: ""
truncate:
   start-after: 166
   end-before: 170
---
source: build/csharp-examples/src/MongoDB.Driver.Examples/QueryPrimer.cs
target: includes/example-csharp-less-than-results.rst
transform: 
  - regex: "^            "
    replace: ""
truncate:
   start-after: 172
   end-before: 174
---
source: build/csharp-examples/src/MongoDB.Driver.Examples/QueryPrimer.cs
target: includes/example-csharp-sort.cs
transform: 
  regex: "^            "
  replace: ""
truncate:
   start-after: 183
   end-before: 188
---
source: build/csharp-examples/src/MongoDB.Driver.Examples/QueryPrimer.cs
target: includes/example-csharp-sort-results.rst
transform: 
  - regex: "^            "
    replace: ""
truncate:
   start-after: 190
   end-before: 193
---
source: build/csharp-examples/src/MongoDB.Driver.Examples/UpdatePrimer.cs
target: includes/example-prereq-csharp-UpdatePrimer.cs
truncate:
   start-after: 14
   end-before: 20
---
source: build/csharp-examples/src/MongoDB.Driver.Examples/UpdatePrimer.cs
target: includes/example-csharp-update-top-level-fields.cs
transform: 
  regex: "^            "
  replace: ""
truncate:
   start-after: 33
   end-before: 40
---
source: build/csharp-examples/src/MongoDB.Driver.Examples/UpdatePrimer.cs
target: includes/example-csharp-update-top-level-fields-results.rst
transform: 
  - regex: "^            "
    replace: ""
truncate:
   start-after: 42
   end-before: 48
---
source: build/csharp-examples/src/MongoDB.Driver.Examples/UpdatePrimer.cs
target: includes/example-csharp-update-embedded-field.cs
transform: 
  regex: "^            "
  replace: ""
truncate:
   start-after: 58
   end-before: 63
---
source: build/csharp-examples/src/MongoDB.Driver.Examples/UpdatePrimer.cs
target: includes/example-csharp-update-embedded-field-results.rst
transform: 
  - regex: "^            "
    replace: ""
truncate:
   start-after: 65
   end-before: 71
---
source: build/csharp-examples/src/MongoDB.Driver.Examples/UpdatePrimer.cs
target: includes/example-csharp-update-multiple-documents.cs
transform: 
  regex: "^            "
  replace: ""
truncate:
   start-after: 81
   end-before: 89
---
source: build/csharp-examples/src/MongoDB.Driver.Examples/UpdatePrimer.cs
target: includes/example-csharp-update-multiple-documents-results.rst
transform: 
  - regex: "^            "
    replace: ""
truncate:
   start-after: 91
   end-before: 97
---
source: build/csharp-examples/src/MongoDB.Driver.Examples/IndexesPrimer.cs
target: includes/example-prereq-csharp-IndexesPrimer.cs
truncate:
   start-after: 14
   end-before: 19
---
source: build/csharp-examples/src/MongoDB.Driver.Examples/IndexesPrimer.cs
target: includes/example-csharp-single-field-index.cs
transform: 
  regex: "^            "
  replace: ""
truncate:
   start-after: 32
   end-before: 36
---
source: build/csharp-examples/src/MongoDB.Driver.Examples/IndexesPrimer.cs
target: includes/example-csharp-single-field-index-results.rst
transform: 
  - regex: "^            "
    replace: ""
truncate:
   start-after: 38
   end-before: 44
---
source: build/csharp-examples/src/MongoDB.Driver.Examples/IndexesPrimer.cs
target: includes/example-csharp-create-compound-index.cs
transform: 
  regex: "^            "
  replace: ""
truncate:
   start-after: 54
   end-before: 58
---
source: build/csharp-examples/src/MongoDB.Driver.Examples/IndexesPrimer.cs
target: includes/example-csharp-create-compound-index-results.rst
transform: 
  - regex: "^            "
    replace: ""
truncate:
   start-after: 60
   end-before: 66
---
source: build/csharp-examples/src/MongoDB.Driver.Examples/RemovePrimer.cs
target: includes/example-prereq-csharp-RemovePrimer.cs
truncate:
   start-after: 14
   end-before: 19
---
source: build/csharp-examples/src/MongoDB.Driver.Examples/RemovePrimer.cs
target: includes/example-csharp-remove-matching-documents.cs
transform: 
  regex: "^            "
  replace: ""
truncate:
   start-after: 31
   end-before: 35
---
source: build/csharp-examples/src/MongoDB.Driver.Examples/RemovePrimer.cs
target: includes/example-csharp-remove-matching-documents-results.rst
transform: 
  - regex: "^            "
    replace: ""
truncate:
   start-after: 37
   end-before: 39
---
source: build/csharp-examples/src/MongoDB.Driver.Examples/RemovePrimer.cs
target: includes/example-csharp-remove-all-documents.cs
transform: 
  regex: "^            "
  replace: ""
truncate:
   start-after: 49
   end-before: 53
---
source: build/csharp-examples/src/MongoDB.Driver.Examples/RemovePrimer.cs
target: includes/example-csharp-remove-all-documents-results.rst
transform: 
  - regex: "^            "
    replace: ""
truncate:
   start-after: 55
   end-before: 57
---
source: build/csharp-examples/src/MongoDB.Driver.Examples/RemovePrimer.cs
target: includes/example-csharp-drop-collection.cs
transform: 
  regex: "^            "
  replace: ""
truncate:
   start-after: 67
   end-before: 69
---
source: build/csharp-examples/src/MongoDB.Driver.Examples/RemovePrimer.cs
target: includes/example-csharp-drop-collection-results.rst
transform: 
  - regex: "^            "
    replace: ""
truncate:
   start-after: 71
   end-before: 77
...