# If migrating as *.rst from another repo,
# Add to .gitignore
#
source: administration/install-on-linux.txt
target: tutorial/install-on-linux.rst
---
source: includes/toc-install-on-linux-landing.yaml
transform:
  regex: "file: /administration/install-on-linux"
  replace: "file: /tutorial/install-on-linux"
---
source: tutorial/install-mongodb-on-red-hat.txt
target: tutorial/install-mongodb-on-red-hat.txt
transform:
  - regex: ":doc:`default ports </reference/default-mongodb-port>`."
    replace: ":manual:`default ports </reference/default-mongodb-port>`."
---
source: tutorial/install-mongodb-on-windows.txt
target: tutorial/install-mongodb-on-windows.rst
transform:
  - regex: ":doc:`/core/security`"
    replace: ":manual:`Security Concepts </core/security>`"
  - regex: ":doc:`/reference/method"
    replace: ":manual:`MongoDB Shell Methods </reference/methods>`"
  - regex: ":doc:`(.*) <(/reference/configuration-options)>`"
    replace: ":manual:`\\1 <\\2>`"
---
source: includes/steps-create-manually-windows-service-for-mongodb.yaml
transform:
  regex: ":doc:`(.*) <(/reference/configuration-options)>`"
  replace: ":manual:`\\1 <\\2>`"
---
source: includes/steps-get-mongodb-for-windows.yaml
transform:
  regex: ":doc:"
  replace: ":manual:"
---
source: includes/steps-install-mongodb-on-windows-unattended.yaml
transform:
  regex: ":doc:"
  replace: ":manual:"
---
source:  includes/fact-selinux-redhat-options.rst
transform:
  regex: ":doc:"
  replace: ":manual:"
---
source: includes/steps-run-mongodb-on-linux.yaml
truncate:
   end-before: "# End-for-getting-started-guide"
---
source: includes/steps-run-mongodb-on-a-linux-distribution.yaml
truncate:
   end-before: "# End-for-getting-started-guide"
---
source: includes/steps-run-mongodb-on-debian.yaml
truncate:
   end-before: "# End-for-getting-started-guide"
---
source: includes/steps-run-mongodb-on-windows.yaml
transform:
  - regex: ":doc:"
    replace: ":manual:"
truncate:
   end-before: "# End-for-getting-started-guide"
---
source: includes/list-mongodb-org-packages.rst
transform:
  regex: ":doc:`(.*) <(.*)>`"
  replace: ":manual:`\\1 <\\2>`"
...