override: false
sources:
  - images/crud-annotated-document.svg
  - images/data-model-normalized.svg
  - images/data-model-denormalized.svg
  - images/replica-set-primary-with-secondary-and-arbiter.svg
  - images/replica-set-primary-with-two-secondaries.svg
  - images/replica-set-read-write-operations-primary.svg
  - images/replica-set-trigger-election.svg
  - images/sharded-cluster-production-architecture.svg
  - images/sharded-collection.svg
  - images/sharding-hash-based.svg
  - images/sharding-migrating.svg
  - images/sharding-range-based.svg
  - images/sharding-splitting.svg
  - images/index-with-query.svg
  - images/aggregation-pipeline.svg
  - images/crud-query-stages.svg
  - images/crud-insert-stages.svg
...