# The items in the ``sphinx`` list are the name of Sphinx builders
# supported by ``sphinx-build``.

editions:
  - 'shell'
  - 'python'
  - 'java'
  - 'cpp'
### --- ####
java-web-base:
  edition: java
  inherit: java-base
  tags:
    - java
    - hosted
    - web
    - website
java-print-base:
  edition: java
  inherit: java-base
  tags:
    - hosted
    - java
    - print

node-web-base:
  edition: node
  inherit: node-base
  tags:
    - node
    - hosted
    - web
    - website
node-print-base:
  edition: node
  inherit: node-base
  tags:
    - hosted
    - node
    - print

python-web-base:
  edition: python
  inherit: python-base
  tags:
    - python
    - web
    - website
python-print-base:
  edition: python
  inherit: python-base
  tags:
    - python
    - print

shell-web-base:
  edition: shell
  inherit: shell-base
  tags:
    - shell
    - web
    - website
shell-print-base:
  edition: shell
  inherit: shell-base
  tags:
    - shell
    - print
cpp-web-base:
  edition: cpp
  inherit: cpp-base
  tags:
    - cpp
    - web
    - website
cpp-print-base:
  edition: cpp
  inherit: cpp-base
  tags:
    - cpp
    - print

### --- ####
dirhtml-python:
  builder: dirhtml
  inherit: python-web-base
html-python:
  builder: html
  inherit: python-web-base
gettext-python:
  builder: gettext
  inherit: python-web-base
singlehtml-python:
  builder: singlehtml
  inherit: python-web-base
epub-python:
  builder: epub
  inherit: python-print-base
latex-python:
  builder: latex
  inherit: python-print-base
json-python:
  builder: json
  inherit: python-web-base

dirhtml-java:
  builder: dirhtml
  inherit: java-web-base
html-java:
  builder: html
  inherit: java-web-base
gettext-java:
  builder: gettext
  inherit: java-web-base
singlehtml-java:
  builder: singlehtml
  inherit: java-web-base
epub-java:
  builder: epub
  inherit: java-print-base
json-java:
  builder: json
  inherit: java-web-base
latex-java:
  builder: latex
  inherit: java-print-base

dirhtml-node:
  builder: dirhtml
  inherit: node-web-base
html-node:
  builder: html
  inherit: node-web-base
gettext-node:
  builder: gettext
  inherit: node-web-base
singlehtml-node:
  builder: singlehtml
  inherit: node-web-base
epub-node:
  builder: epub
  inherit: node-print-base
json-node:
  builder: json
  inherit: node-web-base
latex-node:
  builder: latex
  inherit: node-print-base

dirhtml-shell:
  builder: dirhtml
  inherit: shell-web-base
html-shell:
  builder: html
  inherit: shell-web-base
gettext-shell:
  builder: gettext
  inherit: shell-web-base
singlehtml-shell:
  builder: singlehtml
  inherit: shell-web-base
epub-shell:
  builder: epub
  inherit: shell-print-base
json-shell:
  builder: json
  inherit: shell-web-base
latex-shell:
  builder: latex
  inherit: shell-print-base

dirhtml-cpp:
  builder: dirhtml
  inherit: cpp-web-base
html-cpp:
  builder: html
  inherit: cpp-web-base
gettext-cpp:
  builder: gettext
  inherit: cpp-web-base
singlehtml-cpp:
  builder: singlehtml
  inherit: cpp-web-base
epub-cpp:
  builder: epub
  inherit: cpp-print-base
latex-cpp:
  builder: latex
  inherit: cpp-print-base
json-cpp:
  builder: json
  inherit: cpp-web-base
### --- ####
root-base:
  languages: ['es', 'fr', 'ja', 'it', 'zh']
  tags: ['primer', 'getting-started']
drivers-base:
  inherit: root-base
  tags: 'drivers'
  excluded:
    - /installation.txt
    - /drivers.txt
    - /tutorial/install-mongodb-on-debian.txt
    - /tutorial/install-mongodb-on-linux.txt
    - /tutorial/install-mongodb-on-os-x.txt
    - /tutorial/install-mongodb-on-red-hat.txt
    - /tutorial/install-mongodb-on-ubuntu.txt
    - /tutorial/install-mongodb-on-amazon.txt
    - /tutorial/install-mongodb-on-suse.txt
    - /tutorial/install-mongodb-on-windows.txt
    - /tutorial/install-on-linux.txt
java-base:
  inherit: drivers-base
  edition: java
  excluded: []
python-base:
  inherit: drivers-base
  edition: python
  excluded: []
node-base:
  inherit: drivers-base
  edition: node
  excluded: []
shell-base:
  inherit: root-base
  edition: shell
  tags: 'core'
  excluded: []
cpp-base:
  inherit: drivers-base
  edition: cpp
  excluded: []
...
